# Generated by Django 4.2.3 on 2023-07-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('emai', models.EmailField(max_length=150)),
                ('phone', models.IntegerField(max_length=12)),
                ('desc', models.TextField(max_length=1000)),
            ],
        ),
    ]
