# Generated by Django 4.2.3 on 2023-07-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_date_alter_contact_desc_alter_contact_emai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emai',
            new_name='email',
        ),
    ]
